### ISSUE TITLE
Add params to use proxy

### ISSUE THREAD

**Issue by Kaelatt** [devolo/ssllabs#30]
Hi,
Is possible to add method to make on request with proxy setting? (and add it on Readme)
Thanks, Kaelatt

**Comment by Shutgun** [comment]
Hi @Kaelatt , depending on how you are using this lib, I guess it is already possible. Could you tell me, if you rely on high level usage or the low level usage?

**Comment by Kaelatt** [comment]
I use the librairy for check my domains and subdomains so yes it's for high level usage but i think the api can support it.

If you have a idea to make a request with proxy "proxy.com:80" can you tell me how to make it please.

**Comment by Shutgun** [comment]
So, on the low level usage you can specify your own httpx.Asynclient with configured proxy (https://www.python-httpx.org/advanced/#http-proxying) and pass it with the argument client. 

See https://github.com/devolo/ssllabs/blob/246b948ec936bdcb17bdb10e44a0a05359ea6125/ssllabs/api/_api.py#L14

However, the high level usage does not support that yet. I would have to add that.

**Comment by Kaelatt** [comment]
Danke Schön für alle 

I try the solution and i make a feedback 👍

**Comment by Shutgun** [comment]
@Kaelatt , I just released 1.1.0 which can also take the client for the high level usage. If it does not fit your needs, let me know.

**Comment by Kaelatt** [comment]
@Shutgun It's work perfectly, thanks lot for all. Haben Sie einen guten Tag  👍

**Comment by Shutgun** [comment]
You are very welcome.
