### ISSUE TITLE
Add option to include endpoint details

### ISSUE THREAD

**Issue by alex-gts** [devolo/ssllabs#61]
Hi,

By default, the `analyse` method does not return endpoint details when retrieving an assessment from the cache.
This is because the variable `all` is not set to `done` unless the response is not immediately `READY`. 
I am aware that at this is avoidable by using the low-level functionality, but it would be beneficial to incorporate this at the high level.

```python
# ssllabs/sslabs.py lines 72 - 86

host_object = await a.get(
            host=host,
            startNew="off" if from_cache else "on",
            fromCache="on" if from_cache else "off",
            publish="on" if publish else "off",
            ignoreMismatch="on" if ignore_mismatch else "off",
            maxAge=max_age,
             # all is not set
        )
        self._semaphore.release()
        while host_object.status not in ["READY", "ERROR"]:
            self._logger.debug("Assessment of %s not ready yet.", host)
            await asyncio.sleep(10)
            host_object = await a.get(host=host, all="done") # all is set to "done"
        return host_object
```
Is this by design, or should I create a pull request to add a new parameter for the `analyse` method that controls if endpoint details are returned?

Thank you,
Alex

**Comment by 2Fake** [comment]
It's been a long time since I've worked on this project. Feel free to add this option. Maybe as an optional parameter?

**Comment by alex-gts** [comment]
Thank you, I've opened a PR. #62

**Comment by Shutgun** [comment]
Fixed with #62

**Comment by alex-gts** [comment]
Hi @Shutgun,

I'm trying to migrate my projects back to the upstream package, but I think the PyPI CI is failing due to an authentication error.

**Comment by Shutgun** [comment]
Thanks for the hint, how ever that happend ... I renewed the authentication and pushed the assets again. It available now 👍

**Comment by alex-gts** [comment]
Thank you so much, I really appreciate it
